### ISSUE TITLE
can u write a "how to run" ?

### ISSUE THREAD

**Issue by lxhj** [paralin/go-dota2#12]

**Comment by paralin** [comment]
This repo is intentionally a bit ambiguous because I dont' want to be the source of a flood of bots to Dota2.

**Comment by eVen-gits** [comment]
I know this has already been closed and I understand your sentiment, but I'll ask regardless.

Years ago, I've been using https://github.com/ValvePython/dota2

The goal was to create a discord integrated inhouse league. As it seems, the library was based off of https://github.com/Arcana/node-dota2 and that is discontinued and now points to your work.

The problem is that I don't have any experience with go. Having a sort of starting point would be very helpful.

**Comment by eremenko1** [comment]
up pls

**Comment by eremenko1** [comment]
> eVen

Hello. Did you manage to launch? Please give me a short guide

**Comment by eVen-gits** [comment]
> Hello. Did you manage to launch? Please give me a short guide

Unfortunately - no.

**Comment by RickWillcox** [comment]
I also havent been able to find any example repos to have a look at if anyone does @ me please. Cheers
