### ISSUE TITLE
inviting players to a Dota 2 party

### ISSUE THREAD

**Issue by lpjhelder** [paralin/go-dota2#56]
Hi @paralin 

Firstly, thank you for the go-dota2 library; it's been incredibly helpful for my projects related to Dota 2.

I'm reaching out to inquire about a feature I need but haven't been able to figure out how to implement with the library: inviting players to a Dota 2 party. The documentation has been great for managing lobbies, but my current project necessitates inviting players directly to parties, and I'm unsure of how to proceed.

Could you offer any advice or point me towards the relevant parts of the API for achieving party invites? Even a nudge in the right direction would be immensely appreciated.

Thanks again for your work on go-dota2. Looking forward to your guidance.

Best, Helder

**Comment by paralin** [comment]
Hi, I no longer work with the dota2 apis and am not sure how to do this.

You can attach to Steam using Nethook2 and the analyzer: https://github.com/SteamRE/SteamKit/blob/master/Resources/NetHook2/NetHook2.sln

And view all the messages sent to/from the GC. Then observe what happens when you make a party and invite someone.

Then you can replicate those messages in this library.

Hopefully that gets you pointed in the right direction!
